# Generated by Django 5.0.4 on 2024-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Student',
                'db_table': 'Student',
            },
        ),
    ]
